### ISSUE TITLE
What's Needed to Build Project?

### ISSUE THREAD

**Issue by jbramwell** [madskristensen/ExtensionGallery#6]
Please provide a "readme" file so I can tell what I need to do in order to build the solution. Thanks! :-)

**Comment by rtpHarry** [comment]
You probably had some issues with this because this is based on pre-release asp.net 5 / mvc 6 software.

You need the latest [Visual Studio 2015 RC](https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx) build to compile it.

Mads just accepted a pull request to bring this project up to date with the latest beta4 release of asp.net 5. If you had trouble before you should be able to compile and run it now with the Visual Studio release linked above - until they bring out the next feature-breaking release :)

**Comment by japj** [comment]
FYI ASP.NET5 Beta5 has just been released. I'm not sure if there are related breaking changes again for the ExtensionGallery.

I also heard on the weekly ASP.NET standup video that ASP.NET5 is expected to have a RC near the end of this year. Seeing that there is no 'go-live' license for ASP.NET5 yet, what does that actually mean for using the ExtensionGallery?

**Comment by madskristensen** [comment]
You need ASP.NET 5 beta 5 and Visual Studio 2015 RTM
